package de.rwth.i9.simt.im.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PageRedirects generated by hbm2java
 */
@Entity
@Table(name = "page_redirects", catalog = "enwikidb")
public class WikiPageRedirects implements java.io.Serializable {

	private WikiPageRedirectsId id;

	public WikiPageRedirects() {
	}

	public WikiPageRedirects(WikiPageRedirectsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "redirects", column = @Column(name = "redirects")) })
	public WikiPageRedirectsId getId() {
		return this.id;
	}

	public void setId(WikiPageRedirectsId id) {
		this.id = id;
	}

}
