package de.rwth.i9.simt.im.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "enwikidb", uniqueConstraints = @UniqueConstraint(columnNames = "pageId"))
public class WikiPage implements java.io.Serializable {

	private Long id;
	private Integer pageId;
	private String name;
	private String text;
	private Boolean isDisambiguation;

	public WikiPage() {
	}

	public WikiPage(Integer pageId, String name, String text, Boolean isDisambiguation) {
		this.pageId = pageId;
		this.name = name;
		this.text = text;
		this.isDisambiguation = isDisambiguation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "pageId", unique = true)
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "isDisambiguation")
	public Boolean getIsDisambiguation() {
		return this.isDisambiguation;
	}

	public void setIsDisambiguation(Boolean isDisambiguation) {
		this.isDisambiguation = isDisambiguation;
	}

}
