package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryOutlinksId generated by hbm2java
 */
@Embeddable
public class CategoryOutlinksId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3922300439745295052L;
	private long id;
	private Integer outLinks;

	public CategoryOutlinksId() {
	}

	public CategoryOutlinksId(long id) {
		this.id = id;
	}

	public CategoryOutlinksId(long id, Integer outLinks) {
		this.id = id;
		this.outLinks = outLinks;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "outLinks")
	public Integer getOutLinks() {
		return this.outLinks;
	}

	public void setOutLinks(Integer outLinks) {
		this.outLinks = outLinks;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryOutlinksId))
			return false;
		CategoryOutlinksId castOther = (CategoryOutlinksId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getOutLinks() == castOther.getOutLinks()) || (this.getOutLinks() != null
						&& castOther.getOutLinks() != null && this.getOutLinks().equals(castOther.getOutLinks())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getOutLinks() == null ? 0 : this.getOutLinks().hashCode());
		return result;
	}

}
