package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoryOutlinks generated by hbm2java
 */
@Entity
@Table(name = "category_outlinks", catalog = "simplewikidb")
public class CategoryOutlinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4081470658475362172L;
	private CategoryOutlinksId id;

	public CategoryOutlinks() {
	}

	public CategoryOutlinks(CategoryOutlinksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "outLinks", column = @Column(name = "outLinks")) })
	public CategoryOutlinksId getId() {
		return this.id;
	}

	public void setId(CategoryOutlinksId id) {
		this.id = id;
	}

}
