package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoryPages generated by hbm2java
 */
@Entity
@Table(name = "category_pages", catalog = "simplewikidb")
public class CategoryPages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1753348527463916161L;
	private CategoryPagesId id;

	public CategoryPages() {
	}

	public CategoryPages(CategoryPagesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "pages", column = @Column(name = "pages")) })
	public CategoryPagesId getId() {
		return this.id;
	}

	public void setId(CategoryPagesId id) {
		this.id = id;
	}

}
