package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoryInlinks generated by hbm2java
 */
@Entity
@Table(name = "category_inlinks", catalog = "simplewikidb")
public class CategoryInlinks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5074965065109338280L;
	private CategoryInlinksId id;

	public CategoryInlinks() {
	}

	public CategoryInlinks(CategoryInlinksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "inLinks", column = @Column(name = "inLinks")) })
	public CategoryInlinksId getId() {
		return this.id;
	}

	public void setId(CategoryInlinksId id) {
		this.id = id;
	}

}
