package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PageCategories generated by hbm2java
 */
@Entity
@Table(name = "page_categories", catalog = "simplewikidb")
public class PageCategories implements java.io.Serializable {

	private PageCategoriesId id;

	public PageCategories() {
	}

	public PageCategories(PageCategoriesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "pages", column = @Column(name = "pages")) })
	public PageCategoriesId getId() {
		return this.id;
	}

	public void setId(PageCategoriesId id) {
		this.id = id;
	}

}
