package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PageRedirectsId generated by hbm2java
 */
@Embeddable
public class PageRedirectsId implements java.io.Serializable {

	private long id;
	private String redirects;

	public PageRedirectsId() {
	}

	public PageRedirectsId(long id) {
		this.id = id;
	}

	public PageRedirectsId(long id, String redirects) {
		this.id = id;
		this.redirects = redirects;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "redirects")
	public String getRedirects() {
		return this.redirects;
	}

	public void setRedirects(String redirects) {
		this.redirects = redirects;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PageRedirectsId))
			return false;
		PageRedirectsId castOther = (PageRedirectsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getRedirects() == castOther.getRedirects()) || (this.getRedirects() != null
						&& castOther.getRedirects() != null && this.getRedirects().equals(castOther.getRedirects())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getRedirects() == null ? 0 : this.getRedirects().hashCode());
		return result;
	}

}
