package de.rwth.i9.cimt.ke.model.wikipedia;
// Generated May 7, 2017 1:46:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryPagesId generated by hbm2java
 */
@Embeddable
public class WikiCategoryPagesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4460849298797827810L;
	private long id;
	private Integer pages;

	public WikiCategoryPagesId() {
	}

	public WikiCategoryPagesId(long id) {
		this.id = id;
	}

	public WikiCategoryPagesId(long id, Integer pages) {
		this.id = id;
		this.pages = pages;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "pages")
	public Integer getPages() {
		return this.pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WikiCategoryPagesId))
			return false;
		WikiCategoryPagesId castOther = (WikiCategoryPagesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getPages() == castOther.getPages()) || (this.getPages() != null
						&& castOther.getPages() != null && this.getPages().equals(castOther.getPages())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getPages() == null ? 0 : this.getPages().hashCode());
		return result;
	}

}
